### PR TITLE
Creates join/index.html page for generic join form

### PR DESCRIPTION
**Pull request by abhi12ravi**
Yet to fix CSS on the footer section
Ping @debloper

### CODE REVIEW

**Comment by debloper** [comment]
I think you could just use "../css/styles.css" in the HTML, instead of having to copy over the CSS.

**Comment by abhi12ravi** [comment]
@debloper The HTML files in /join/ use a different set of styles. That's why we have /join/css/style.css

**Comment by debloper** [comment]
Why using different style is required?

A subpage of a website is supposed to align on the styling, right?
(Unless for very good reason, which I'm failing to see).

Also, if you were working on gh-pages branch - I could actually see the live page on abhi12ravi.github.io/homepage/join - which isn't possible, as you've changed the branch name. (Non-major issue)

**Comment by abhi12ravi** [comment]
On Wed, Jul 15, 2015 at 10:42 PM, Soumya Deb <notifications@github.com>
wrote:

> Why using different style is required?
>
okay that's what I was trying to do at the start. I'll send another PR

> A subpage of a website is supposed to align on the styling, right?
> (Unless for very good reason, which I'm failing to see).
>

True. I'll stick to this

> Also, if you were working on gh-pages branch - I could actually see the
> live page on abhi12ravi.github.io/homepage/join - which isn't possible,
> as you've changed the branch name. (Non-major issue)
>

Aah the "join-mozin" and gh-pages branch is even.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaIndia/homepage/pull/57#issuecomment-121682507>.
>



-- 
Regards,
Abhiram Ravikumar
Regional Ambassador Lead, Mozilla
http://abhiramrk.com/

**Comment by kaustavdm** [comment]
@abhi12ravi The point that @debloper mentioned was that you directly link to the CSS file in the repository instead of creating a copy of it, like:

```html
<link rel="stylesheet" type="text/css" href="../css/style.css" />
```

**Pull request merged**
